# Generated by Django 3.2.7 on 2021-11-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_movie_data_movie_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Movie_genre',
        ),
        migrations.AddField(
            model_name='movie_data',
            name='genre_ids',
            field=models.ManyToManyField(to='community.Genre'),
        ),
    ]
