# Generated by Django 3.2.7 on 2021-11-19 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20211119_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_data',
            old_name='rank',
            new_name='vote_average',
        ),
    ]
