# Generated by Django 3.2.7 on 2021-11-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_rename_rank_movie_data_vote_average'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='name',
        ),
    ]
