# Generated by Django 3.2.7 on 2021-11-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_rename_genre_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_data',
            name='vote_average',
            field=models.FloatField(),
        ),
    ]
