# Generated by Django 3.2.7 on 2021-11-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_movie_data_vote_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.TextField(),
        ),
    ]
