# Generated by Django 3.2.7 on 2021-11-21 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_genre_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_data',
            name='genre_ids',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Movie_data',
        ),
    ]
