# Generated by Django 3.2.9 on 2021-11-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_genre',
            name='id_10752',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_genre',
            name='id_10770',
            field=models.BooleanField(default=False),
        ),
    ]
