# Generated by Django 3.2.9 on 2021-11-21 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211121_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_genre',
            name='id_10752',
        ),
        migrations.RemoveField(
            model_name='user_genre',
            name='id_10770',
        ),
        migrations.AddField(
            model_name='user_genre',
            name='like_genres',
            field=models.ManyToManyField(blank=True, related_name='liking_genres', to=settings.AUTH_USER_MODEL),
        ),
    ]
