# Generated by Django 3.2.9 on 2021-11-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_genre_like_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_genre',
            name='like_genres_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
