# Generated by Django 3.2.9 on 2021-11-21 22:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_genre_like_genres_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_genre',
            name='like_genres',
            field=models.ManyToManyField(blank=True, related_name='like_genres', to=settings.AUTH_USER_MODEL),
        ),
    ]
